#!/bin/sh

set -e

case "$2" in
    suspend | hybrid-sleep)
        case "$1" in
            pre)
                modprobe -r psmouse
                ;;
            post)
                modprobe psmouse
                ;;
        esac
        ;;
esac
